version: '3'

services:
  backend:
    build:
      context: .
    command: python main.py
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
        context: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - backend